### ISSUE TITLE
Unable to push to netapp repository

### ISSUE THREAD

**Issue by NaniteBased** [EVOLVED-5G/SDK-CLI#21]
* Evolved5G_CLI version: 0.2.6 (through pip)
* Python version: 3.7.2
* Operating System: Windows 10

### Description

I'm trying to create a new netapp repository for testing purposes, but the script fails when pushing to the repository (the repository itself is created fine).

### What I Did

I created a new virtualenv with Python 3.7.2 and installed the CLI tools via pip. At first I had a problem with the script because it could not find the 'invoke' module, but I could solve that by manually installing the package beforehand.

I used the default options for all questions except for the first five, where I used my credentials (no collaborators). Then the script fails with:

```
error: src refspec master does not match any
error: failed to push some refs to 'github.com:EVOLVED-5G/UmaTest.git'
```

The complete output is:

```
Initialized empty Git repository in C:/EVOLVED/NetAppTest/UmaTest/.git/
[main (root-commit) 0792d08] Creation of a new NetApp example-netapp
 11 files changed, 335 insertions(+)
 create mode 100644 Dockerfile
 create mode 100644 README.md
 create mode 100644 iac/slave/Dockerfile
 create mode 100644 iac/terraform/backend.tf
 create mode 100644 iac/terraform/main.tf
 create mode 100644 iac/terraform/provider.tf
 create mode 100644 pac/Jenkins-build.groovy
 create mode 100644 pac/Jenkins-deploy.groovy
 create mode 100644 pac/Jenkins-destroy.groovy
 create mode 100644 src/README.md
 create mode 100644 src/index.html
Repository created <Response [201]>
error: src refspec master does not match any
error: failed to push some refs to 'github.com:EVOLVED-5G/UmaTest.git'
Traceback (most recent call last):
  File "C:\Users\Bruno\AppData\Local\Temp\tmpsbfpazi2.py", line 185, in <module>
    main()
  File "C:\Users\Bruno\AppData\Local\Temp\tmpsbfpazi2.py", line 180, in main
    PostGenProjectHook().run()
  File "C:\Users\Bruno\AppData\Local\Temp\tmpsbfpazi2.py", line 171, in run
    self.git_repo()
  File "C:\Users\Bruno\AppData\Local\Temp\tmpsbfpazi2.py", line 141, in git_repo
    self.git_push()
  File "C:\Users\Bruno\AppData\Local\Temp\tmpsbfpazi2.py", line 116, in git_push
    run(command)
  File "c:\evolved\netapptest\venv\lib\site-packages\invoke\__init__.py", line 48, in run
    return Context().run(command, **kwargs)
  File "c:\evolved\netapptest\venv\lib\site-packages\invoke\context.py", line 95, in run
    return self._run(runner, command, **kwargs)
  File "c:\evolved\netapptest\venv\lib\site-packages\invoke\context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "c:\evolved\netapptest\venv\lib\site-packages\invoke\runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "c:\evolved\netapptest\venv\lib\site-packages\invoke\runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "c:\evolved\netapptest\venv\lib\site-packages\invoke\runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'git push -u origin master'

Exit code: 1

Stdout: already printed

Stderr: already printed


Stopping generation because post_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "c:\users\bruno\appdata\local\programs\python\python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bruno\appdata\local\programs\python\python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\EVOLVED\NetAppTest\venv\Scripts\evolved5g.exe\__main__.py", line 7, in <module>
  File "c:\evolved\netapptest\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\evolved\netapptest\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\evolved\netapptest\venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\evolved\netapptest\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\evolved\netapptest\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\evolved\netapptest\venv\lib\site-packages\evolved5g\cli.py", line 47, in generate
    cookiecutter_generate(location, no_input=no_input, extra_context=extra)
  File "c:\evolved\netapptest\venv\lib\site-packages\evolved5g\utils.py", line 8, in cookiecutter_generate
    cookiecutter(location, no_input=no_input, extra_context=extra_context)
  File "c:\evolved\netapptest\venv\lib\site-packages\cookiecutter\main.py", line 106, in cookiecutter
    output_dir=output_dir,
  File "c:\evolved\netapptest\venv\lib\site-packages\cookiecutter\generate.py", line 362, in generate_files
    repo_dir, 'post_gen_project', project_dir, context, delete_project_on_failure
  File "c:\evolved\netapptest\venv\lib\site-packages\cookiecutter\generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "c:\evolved\netapptest\venv\lib\site-packages\cookiecutter\hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "c:\evolved\netapptest\venv\lib\site-packages\cookiecutter\hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "c:\evolved\netapptest\venv\lib\site-packages\cookiecutter\hooks.py", line 87, in run_script
    'Hook script failed (exit status: {})'.format(exit_status)
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)
```

If I check here on Github I can see that the repo is there, but empty. Locally I can see that the files are created, but they are deleted after the error.

**Comment by skolome** [comment]
Hi! I don't think this will solve your issue, but install via "pip" is not yet very stable. I updated the package to the latest version, but you should install from sources preferably. I believe the issue is somewhere else, but please update and try again. Thanks

**Comment by rimarala** [comment]
Hi Bruno,

We have tried to replicate your error, unfortunately we were be able to do so. Although, it seems in latest version Git name the repository main rather than master, but we have installed from pip the evolved5g package, then execute the command evovled5g generate and it works, do the push correctly.
We have also tried to create a branch previously using the GUI, which create a main branch but again the push has been done properly and a new branch (master) has created.
Further, we have used your repository and we have been able to create a branch by using the command evolved5g generate, so if you go to your repo you will see now a branch master (but assigned to Paula, for testing purposes).
Could you please provide a step by step guide to try to replicate your error? 

Thanks.

**Comment by NaniteBased** [comment]
Hello, 

Aside from installing the package on a virtualenv I did not make any changes to the steps in the instructions, but I've done some more tests and the problem seems to be Windows-specific.

I did the same on an Ubuntu machine (this time I got version 0.5.0) and everything ran fine, but on Windows I still get the same error, even after updating the package. Also, if I try to install from source I get the following error:

```
Traceback (most recent call last):
  File ".\setup.py", line 9, in <module>
    readme = readme_file.read()
  File "C:\EVOLVED\NetAppTest2\venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4461: character maps to <undefined>
```

Which looks similar to the problems with Windows/Linux line endings, but I haven't checked (I've also not tried building on Linux yet).

I'll let you know if I find something else.

**Comment by rimarala** [comment]
Hello,

We have tried to "emulate" your same environment, which is to create a venv in Windows (_python3 -m venv /path/to/new/virtual/environment_) and it also work for us. Please find our configuration Below:

- Evolved5G_CLI version: 0.5.0 (through pip)
- Python version: 3.10
- Pip version: 21.2.3
- Operating System: Windows 10

**Comment by NaniteBased** [comment]
Hello, I tried using Python 3.10 but the issue remains. I've also tried using Powershell and Git Bash and the error appears on both, so it does not seem to be an issue with the terminal either.

Maybe it's the git version? I'm using 2.33.0.windows.2.

**Comment by NaniteBased** [comment]
Hi again. I tried following the steps in the script manually and it certainly looks like a `master` vs `main` problem.

When I make a git init and a commit the branch name is automatically set to `main`, and trying to push it as `master` generates the error. If I push to `main` instead everything runs fine:

```
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git add --all
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git commit -m "Creation of a new NetApp example-netapp"
[main (root-commit) cb02df0] Creation of a new NetApp example-netapp
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git remote add origin git@github.com:EVOLVED-5G/UmaTest2.git
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git push -u origin master
error: src refspec master does not match any
error: failed to push some refs to 'github.com:EVOLVED-5G/UmaTest2.git'
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git status
On branch main
nothing to commit, working tree clean
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git log
commit cb02df0f2e2787344b01e8fa3855235a82af8822 (HEAD -> main)
Author: nanitebased <####>
Date:   Thu Nov 4 09:13:58 2021 +0100

    Creation of a new NetApp example-netapp
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2> git push -u origin main
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 235 bytes | 235.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:EVOLVED-5G/UmaTest2.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
(venv) PS C:\EVOLVED\NetAppTest3\UmaTest2>
```

**Comment by rimarala** [comment]
Hello,

We have checked our git version and it was 2.31.1.windows.1, to emulate your scenario we have updated our git version to 2.33.1.windows.1 which is the same as yours, during the installation process it asked if we want the new "main" option which has been selected to try to replicate your scenario. 
Once installed, we have runned evolved5g generate and it works fine, could you have any configuration file in your own which somehow overwrites the python script?

**Comment by NaniteBased** [comment]
Hello. I checked my config and my `init.defaultBranch` is indeed `main`. I've updated my git also to 2.33.1.windows.1 to check if this has changed in the latest version but I still see the same error, no idea what else may be different from your setup now.

Still, this may be easy to fix since you can force a particular branch name on `git init` with the `-b` parameter, that should make the script work independently of the user configuration.
